import os
import argparse
import re

def parse_combined_file(input_file):
    """
    Parses the combined file and returns a list of tuples (file_path, content).
    The function expects markers in the format: /* File: path/to/file.ext */
    """
    file_entries = []
    current_file = None
    current_lines = []
    file_marker_pattern = re.compile(r"/\*\s*File:\s*(.*?)\s*\*/")

    with open(input_file, 'r', encoding='utf-8') as f:
        for line in f:
            marker_match = file_marker_pattern.match(line.strip())
            if marker_match:
                # Save previous file entry if exists
                if current_file is not None:
                    file_entries.append((current_file, ''.join(current_lines)))
                    current_lines = []
                current_file = marker_match.group(1)
            else:
                if current_file is not None:
                    current_lines.append(line)
        # Append the last file entry if present
        if current_file is not None:
            file_entries.append((current_file, ''.join(current_lines)))
    return file_entries

def recreate_files(entries):
    """
    For each (file_path, content) tuple, create any necessary directories and
    write the content into the file (overwriting if it exists).
    """
    for file_path, content in entries:
        directory = os.path.dirname(file_path)
        if directory and not os.path.exists(directory):
            os.makedirs(directory, exist_ok=True)
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Updated file: {file_path}")

def main():
    parser = argparse.ArgumentParser(
        description="Recreate/update files and their folders from a combined text file."
    )
    parser.add_argument("input_file", help="Path to the combined text file generated by the concatenation script")
    args = parser.parse_args()

    entries = parse_combined_file(args.input_file)
    if not entries:
        print("No file entries found in the combined file.")
    else:
        recreate_files(entries)
        print("All files have been recreated/updated.")

if __name__ == '__main__':
    main()
